import type { Metadata } from "next";
import { Nunito } from "next/font/google";
import "./globals.css";

import { repositoryName } from "@/prismicio";
import { PrismicPreview } from "@prismicio/next";

const sans = Nunito({
	subsets: ["latin"],
	variable: "--font-sans",
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body className={`${sans.variable} antialiased`}>{children}</body>
			<PrismicPreview repositoryName={repositoryName} />
		</html>
	);
}
